version: "3.8"
services:
  postgres:
    image: postgis/postgis
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - "data:/var/lib/postgresql/data"
    networks:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - BACK_PORT=5000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - SENDGRID_KEY=${SENDGRID_KEY}
    networks:
      - backend
      - frontend
  frontend:
    build: ./dashboard
    ports:
      - "8501:8501"
    networks:
      - frontend
    environment:
      - FRONT_PORT=8501
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - BACK_URL=${BACK_URL}

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  data:
