version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=postgres
      - PORT=5000
    networks:
      - covid_data

networks:
  covid_data:
    external:
      name: covid_data
